### ISSUE TITLE
Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0' when running on Linux

### ISSUE THREAD

**Issue by Flavien** [aspnet/Microsoft.Data.Sqlite#135]
I am trying to use Microsoft.Data.Sqlite on the CoreCLR (Beta 7) on Linux (Ubuntu 14.04). I am getting the following exception:

```
 System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.Interop.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Framework.Internal.NativeLibraryLoader.GetModuleHandle(String lpModuleName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.IsLoaded(String dllName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.TryLoad(String dllName, String applicationBase)
   at Microsoft.Data.Sqlite.Interop.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OpenChain.Sqlite.SqliteTransactionStore..ctor(String filename)
   at OpenChain.Sqlite.SqliteLedgerQueries..ctor(String filename)
   at OpenChain.Server.Models.ConfigurationParser.CreateLedgerStore(IServiceProvider serviceProvider)
---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.Interop.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Framework.Internal.NativeLibraryLoader.GetModuleHandle(String lpModuleName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.IsLoaded(String dllName)
   at Microsoft.Framework.Internal.NativeLibraryLoader.TryLoad(String dllName, String applicationBase)
   at Microsoft.Data.Sqlite.Interop.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)<---
```

Any idea how to solve this?

**Comment by natemcmaster** [comment]
See https://github.com/aspnet/Microsoft.Data.Sqlite/issues/133#issuecomment-137595038.

This is a known issue and has been fixed for beta 8.

**Comment by Flavien** [comment]
In which package is the fix located? I've tried upgrading Microsoft.Data.Sqlite to `1.0.0-beta8-15070`, and keep the rest at beta7, and this still doesn't work.

Can I just upgrade a particular package, or do I need to update everything?

**Comment by natemcmaster** [comment]
15531 and up.

> Can I just upgrade a particular package, or do I need to update everything?
Best to work with coherent sets of packages (either use nightly builds for everything or only use stable builds. Mixing will lead to instability.)
